'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.9151
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TXT.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _2021_08_23__12_28__21_714_giscc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2021-08-23__12-28__21-714-giscc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bolin01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bolin01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bolincito1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bolincito1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bolita01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bolita01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bolita02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bolita02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Campanada() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Campanada", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property goma() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("goma", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property May() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("May", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Scroll() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scroll", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property tic() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("tic", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property tica() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("tica", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property tilde() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("tilde", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
